# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Mon Sep  2 15:30:24 2019
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class AtaqueDialog_Ui(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AtaqueDialog_Ui.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((798, 517))
        self.tabs = wx.Notebook(self, wx.ID_ANY)
        self.tab_info = wx.Panel(self.tabs, wx.ID_ANY)
        self.txt_resumen = wx.TextCtrl(self.tab_info, wx.ID_ANY, "", style=wx.TE_MULTILINE | wx.TE_READONLY | wx.TE_RICH2)
        self.txt_notas = wx.TextCtrl(self.tab_info, wx.ID_ANY, "", style=wx.TE_MULTILINE)
        self.btn_save_notas = wx.Button(self.tab_info, wx.ID_ANY, "Guardar")
        self.tab_ataque = wx.Panel(self.tabs, wx.ID_ANY)
        self.tab_output = wx.Panel(self.tabs, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AtaqueDialog_Ui.__set_properties
        self.SetTitle("Ataque a ESSID")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("/home/q/dev/wpstool/src/icons/scanner_redes.bmp", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((798, 517))
        self.txt_resumen.SetBackgroundColour(wx.Colour(222, 222, 222))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AtaqueDialog_Ui.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.StaticBoxSizer(wx.StaticBox(self.tab_info, wx.ID_ANY, "Notas"), wx.VERTICAL)
        sizer_9 = wx.StaticBoxSizer(wx.StaticBox(self.tab_info, wx.ID_ANY, "Resumen"), wx.VERTICAL)
        sizer_9.Add(self.txt_resumen, 1, wx.ALL | wx.EXPAND, 5)
        sizer_2.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_2.Add((20, 20), 0, 0, 0)
        sizer_8.Add(self.txt_notas, 1, wx.EXPAND, 0)
        sizer_8.Add(self.btn_save_notas, 0, wx.EXPAND, 0)
        sizer_2.Add(sizer_8, 1, wx.EXPAND, 0)
        self.tab_info.SetSizer(sizer_2)
        sizer_10.Add((0, 0), 0, 0, 0)
        sizer_10.Add((0, 0), 0, 0, 0)
        self.tab_ataque.SetSizer(sizer_10)
        self.tabs.AddPage(self.tab_info, "Info")
        self.tabs.AddPage(self.tab_ataque, "Ataque")
        self.tabs.AddPage(self.tab_output, "Output")
        sizer_1.Add(self.tabs, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class AtaqueDialog_Ui
