# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Mon Sep  2 15:30:24 2019
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainWin_Ui(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainWin_Ui.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.MINIMIZE_BOX | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((835, 525))
        self.statusbar = self.CreateStatusBar(2, wx.STB_ELLIPSIZE_START)
        self.tabs = wx.Notebook(self, wx.ID_ANY)
        self.tab_scan = wx.Panel(self.tabs, wx.ID_ANY)
        self.combo_iface = wx.ComboBox(self.tab_scan, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_READONLY | wx.CB_SIMPLE)
        self.txt_iface_modo = wx.TextCtrl(self.tab_scan, wx.ID_ANY, "", style=wx.TE_READONLY | wx.TE_RIGHT)
        self.txt_iface_power = wx.TextCtrl(self.tab_scan, wx.ID_ANY, "", style=wx.TE_READONLY | wx.TE_RIGHT)
        self.btn_select_iface = wx.Button(self.tab_scan, wx.ID_ANY, "Usar la interfaz seleccionada")
        self.btn_airmon_toggle = wx.Button(self.tab_scan, wx.ID_ANY, "Activar/Desactivar el modo Monitor")
        self.btn_airmon_check = wx.Button(self.tab_scan, wx.ID_ANY, "Optimize Monitor Mode")
        self.btn_powerup = wx.Button(self.tab_scan, wx.ID_ANY, "Aumentar Potencia (solo si la tarjeta lo permite)")
        self.combo_canal = wx.ComboBox(self.tab_scan, wx.ID_ANY, choices=["Todos", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14"], style=wx.CB_DROPDOWN | wx.CB_READONLY | wx.CB_SIMPLE)
        self.txt_timeout = wx.TextCtrl(self.tab_scan, wx.ID_ANY, "60", style=wx.TE_RIGHT)
        self.btn_scan = wx.Button(self.tab_scan, wx.ID_ANY, "Escanear")
        self.tab_redes = wx.Panel(self.tabs, wx.ID_ANY)
        self.lista_redes = wx.ListCtrl(self.tab_redes, wx.ID_ANY, style=wx.LC_AUTOARRANGE | wx.LC_HRULES | wx.LC_REPORT | wx.LC_SINGLE_SEL | wx.LC_SORT_ASCENDING | wx.LC_SORT_DESCENDING | wx.LC_VRULES)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_COMBOBOX, self.on_combo_iface_changed, self.combo_iface)
        self.Bind(wx.EVT_BUTTON, self.on_btn_select_iface, self.btn_select_iface)
        self.Bind(wx.EVT_BUTTON, self.on_btn_airmon_toggle, self.btn_airmon_toggle)
        self.Bind(wx.EVT_BUTTON, self.on_btn_airmon_check, self.btn_airmon_check)
        self.Bind(wx.EVT_BUTTON, self.on_btn_powerup, self.btn_powerup)
        self.Bind(wx.EVT_BUTTON, self.on_btn_scan, self.btn_scan)
        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.on_lista_select_red, self.lista_redes)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainWin_Ui.__set_properties
        self.SetTitle("WPSTool")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("/home/q/dev/wpstool/src/icons/logo_app.bmp", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.statusbar.SetStatusWidths([-1, 200])

        # statusbar fields
        statusbar_fields = ["", "Selecciona una Interfaz"]
        for i in range(len(statusbar_fields)):
            self.statusbar.SetStatusText(statusbar_fields[i], i)
        self.txt_iface_modo.SetBackgroundColour(wx.Colour(201, 201, 201))
        self.txt_iface_power.SetBackgroundColour(wx.Colour(201, 201, 201))
        self.combo_canal.SetSelection(0)
        self.txt_timeout.SetToolTip("Tiempo de escaneo")
        self.btn_scan.SetToolTip("Escanear en busca de redes")
        self.lista_redes.AppendColumn("essid", format=wx.LIST_FORMAT_LEFT, width=150)
        self.lista_redes.AppendColumn("bssid", format=wx.LIST_FORMAT_LEFT, width=200)
        self.lista_redes.AppendColumn("channel", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.lista_redes.AppendColumn("power", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.lista_redes.AppendColumn("lock", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.lista_redes.AppendColumn("vendor", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.lista_redes.AppendColumn("wps", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.lista_redes.AppendColumn("progress", format=wx.LIST_FORMAT_LEFT, width=-1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainWin_Ui.__do_layout
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.StaticBoxSizer(wx.StaticBox(self.tab_scan, wx.ID_ANY, "Escanear Redes"), wx.VERTICAL)
        sizer_5 = wx.StaticBoxSizer(wx.StaticBox(self.tab_scan, wx.ID_ANY, "Selecciona Interface"), wx.VERTICAL)
        sizer_5.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_5.Add(self.combo_iface, 0, wx.EXPAND, 0)
        sizer_5.Add(self.txt_iface_modo, 0, wx.EXPAND, 0)
        sizer_5.Add(self.txt_iface_power, 0, wx.EXPAND, 0)
        sizer_5.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_5.Add(self.btn_select_iface, 0, wx.EXPAND, 0)
        sizer_5.Add((20, 100), 0, wx.EXPAND, 0)
        sizer_5.Add(self.btn_airmon_toggle, 0, wx.EXPAND, 0)
        sizer_5.Add(self.btn_airmon_check, 0, wx.EXPAND, 0)
        sizer_5.Add(self.btn_powerup, 0, wx.EXPAND, 0)
        sizer_4.Add(sizer_5, 1, wx.ALIGN_CENTER | wx.EXPAND, 0)
        sizer_4.Add((20, 20), 0, 0, 0)
        sizer_6.Add((20, 20), 0, 0, 0)
        sizer_6.Add(self.combo_canal, 0, wx.EXPAND, 0)
        sizer_6.Add(self.txt_timeout, 0, wx.EXPAND, 0)
        sizer_6.Add(self.btn_scan, 0, wx.EXPAND, 0)
        sizer_4.Add(sizer_6, 1, wx.EXPAND, 0)
        self.tab_scan.SetSizer(sizer_4)
        sizer_7.Add(self.lista_redes, 1, wx.EXPAND, 0)
        self.tab_redes.SetSizer(sizer_7)
        self.tabs.AddPage(self.tab_scan, "Escanear")
        self.tabs.AddPage(self.tab_redes, "Redes")
        sizer_3.Add(self.tabs, 1, wx.ALL | wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        self.Layout()
        # end wxGlade

    def on_combo_iface_changed(self, event):  # wxGlade: MainWin_Ui.<event_handler>
        print("Event handler 'on_combo_iface_changed' not implemented!")
        event.Skip()

    def on_btn_select_iface(self, event):  # wxGlade: MainWin_Ui.<event_handler>
        print("Event handler 'on_btn_select_iface' not implemented!")
        event.Skip()

    def on_btn_airmon_toggle(self, event):  # wxGlade: MainWin_Ui.<event_handler>
        print("Event handler 'on_btn_airmon_toggle' not implemented!")
        event.Skip()

    def on_btn_airmon_check(self, event):  # wxGlade: MainWin_Ui.<event_handler>
        print("Event handler 'on_btn_airmon_check' not implemented!")
        event.Skip()

    def on_btn_powerup(self, event):  # wxGlade: MainWin_Ui.<event_handler>
        print("Event handler 'on_btn_powerup' not implemented!")
        event.Skip()

    def on_btn_scan(self, event):  # wxGlade: MainWin_Ui.<event_handler>
        print("Event handler 'on_btn_scan' not implemented!")
        event.Skip()

    def on_lista_select_red(self, event):  # wxGlade: MainWin_Ui.<event_handler>
        print("Event handler 'on_lista_select_red' not implemented!")
        event.Skip()

# end of class MainWin_Ui
