# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.4 on Fri Sep 27 22:40:21 2019
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MainWin_Ui(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainWin_Ui.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.MINIMIZE_BOX | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((835, 525))
        self.statusbar = self.CreateStatusBar(2, wx.STB_DEFAULT_STYLE | wx.STB_ELLIPSIZE_START)
        self.tabs = wx.Notebook(self, wx.ID_ANY)
        self.tab_scan = wx.Panel(self.tabs, wx.ID_ANY)
        self.combo_iface = wx.ComboBox(self.tab_scan, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_READONLY | wx.CB_SIMPLE)
        self.txt_iface_modo = wx.TextCtrl(self.tab_scan, wx.ID_ANY, "", style=wx.TE_READONLY | wx.TE_RIGHT)
        self.txt_iface_power = wx.TextCtrl(self.tab_scan, wx.ID_ANY, "", style=wx.TE_READONLY | wx.TE_RIGHT)
        self.btn_select_iface = wx.Button(self.tab_scan, wx.ID_ANY, "Usar la interfaz seleccionada")
        self.btn_airmon_toggle = wx.Button(self.tab_scan, wx.ID_ANY, "Activar/Desactivar el modo Monitor")
        self.btn_airmon_check = wx.Button(self.tab_scan, wx.ID_ANY, "Optimize Monitor Mode")
        self.btn_powerup = wx.Button(self.tab_scan, wx.ID_ANY, "Aumentar Potencia (solo si la tarjeta lo permite)")
        self.combo_canal = wx.ComboBox(self.tab_scan, wx.ID_ANY, choices=["Todos", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14"], style=wx.CB_DROPDOWN | wx.CB_READONLY | wx.CB_SIMPLE)
        self.spin_timeout = wx.SpinCtrl(self.tab_scan, wx.ID_ANY, "30", min=10, max=120, style=0)
        self.txt_timeout = wx.TextCtrl(self.tab_scan, wx.ID_ANY, "30", style=wx.TE_RIGHT)
        self.btn_scan = wx.Button(self.tab_scan, wx.ID_ANY, "Escanear")
        self.tab_redes = wx.Panel(self.tabs, wx.ID_ANY)
        self.lista_redes = wx.ListCtrl(self.tab_redes, wx.ID_ANY, style=wx.LC_AUTOARRANGE | wx.LC_HRULES | wx.LC_REPORT | wx.LC_SINGLE_SEL | wx.LC_SORT_ASCENDING | wx.LC_SORT_DESCENDING | wx.LC_VRULES)
        self.tab_output = wx.Panel(self.tabs, wx.ID_ANY)
        self.txt_output = wx.TextCtrl(self.tab_output, wx.ID_ANY, "   ###########\n  #    WPSTool    #\n ##########\n\n", style=wx.HSCROLL | wx.TE_MULTILINE | wx.TE_READONLY | wx.TE_RICH2)
        self.btn_clear_output = wx.Button(self.tab_output, wx.ID_ANY, "Clear")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_COMBOBOX, self.on_combo_iface_changed, self.combo_iface)
        self.Bind(wx.EVT_BUTTON, self.on_btn_select_iface, self.btn_select_iface)
        self.Bind(wx.EVT_BUTTON, self.on_btn_airmon_toggle, self.btn_airmon_toggle)
        self.Bind(wx.EVT_BUTTON, self.on_btn_airmon_check, self.btn_airmon_check)
        self.Bind(wx.EVT_BUTTON, self.on_btn_powerup, self.btn_powerup)
        self.Bind(wx.EVT_BUTTON, self.on_btn_scan, self.btn_scan)
        self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.on_lista_select_red, self.lista_redes)
        self.Bind(wx.EVT_BUTTON, self.on_button_clear_output, self.btn_clear_output)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MainWin_Ui.__set_properties
        self.SetTitle("WPSTool")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("/home/q/dev/wpstool/src/icons/logo_app.bmp", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.statusbar.SetStatusWidths([-1, 200])

        # statusbar fields
        statusbar_fields = ["", "Selecciona una Interfaz"]
        for i in range(len(statusbar_fields)):
            self.statusbar.SetStatusText(statusbar_fields[i], i)
        self.combo_iface.SetToolTip("Interfaces de red")
        self.txt_iface_modo.SetBackgroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_BACKGROUND))
        self.txt_iface_modo.SetToolTip("Modo de la interfaz")
        self.txt_iface_power.SetBackgroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_BACKGROUND))
        self.txt_iface_power.SetToolTip("Potencia de la interfaz")
        self.btn_select_iface.SetToolTip("Define la interfaz seleccionada como la interfaz por defecto")
        self.btn_airmon_toggle.SetToolTip("Activa o desactiva el modo monitor de la interfaz seleccionada")
        self.btn_airmon_check.SetToolTip("Detiene servicios/aplicaciones que interfieren con el modo monitor")
        self.btn_powerup.SetToolTip("Aumenta la potencia hasta 30dbm (si la interfaz lo permite)")
        self.combo_canal.SetToolTip("Lista de canales a escanear")
        self.combo_canal.SetSelection(0)
        self.spin_timeout.SetMinSize((215, 36))
        self.spin_timeout.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Noto Sans"))
        self.spin_timeout.SetToolTip("Tiempo de escaneo en segundos")
        self.txt_timeout.SetToolTip("Tiempo de escaneo en segundos")
        self.btn_scan.SetToolTip("Escanear en busca de redes")
        self.lista_redes.AppendColumn("essid", format=wx.LIST_FORMAT_LEFT, width=150)
        self.lista_redes.AppendColumn("bssid", format=wx.LIST_FORMAT_LEFT, width=200)
        self.lista_redes.AppendColumn("channel", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.lista_redes.AppendColumn("power", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.lista_redes.AppendColumn("lock", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.lista_redes.AppendColumn("vendor", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.lista_redes.AppendColumn("wps", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.lista_redes.AppendColumn("progress", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.txt_output.SetBackgroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_BACKGROUND))
        self.btn_clear_output.SetFocus()
        self.btn_clear_output.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainWin_Ui.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        layout_tab_scanner = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13 = wx.StaticBoxSizer(wx.StaticBox(self.tab_scan, wx.ID_ANY, "Escanear"), wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(3, 2, 5, 5)
        layout_iface = wx.StaticBoxSizer(wx.StaticBox(self.tab_scan, wx.ID_ANY, "Selecciona Interface"), wx.VERTICAL)
        layout_iface.Add((20, 20), 0, wx.EXPAND, 0)
        layout_iface.Add(self.combo_iface, 0, wx.ALL | wx.EXPAND, 1)
        layout_iface.Add(self.txt_iface_modo, 0, wx.EXPAND, 0)
        layout_iface.Add(self.txt_iface_power, 0, wx.EXPAND, 0)
        layout_iface.Add((20, 20), 0, wx.EXPAND, 0)
        layout_iface.Add(self.btn_select_iface, 0, wx.EXPAND, 0)
        layout_iface.Add((20, 100), 0, wx.EXPAND, 0)
        layout_iface.Add(self.btn_airmon_toggle, 0, wx.EXPAND, 0)
        layout_iface.Add(self.btn_airmon_check, 0, wx.EXPAND, 0)
        layout_iface.Add(self.btn_powerup, 0, wx.EXPAND, 0)
        layout_tab_scanner.Add(layout_iface, 1, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 10)
        layout_tab_scanner.Add((20, 20), 0, wx.EXPAND, 0)
        label_3 = wx.StaticText(self.tab_scan, wx.ID_ANY, "Lista de canales:")
        label_3.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Noto Sans"))
        grid_sizer_1.Add(label_3, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 5)
        grid_sizer_1.Add(self.combo_canal, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL | wx.EXPAND | wx.FIXED_MINSIZE, 0)
        label_1 = wx.StaticText(self.tab_scan, wx.ID_ANY, "Tiempo de escaneo:")
        label_1.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Noto Sans"))
        grid_sizer_1.Add(label_1, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 5)
        grid_sizer_1.Add(self.spin_timeout, 1, wx.ALIGN_RIGHT | wx.ALL | wx.EXPAND | wx.FIXED_MINSIZE, 1)
        label_2 = wx.StaticText(self.tab_scan, wx.ID_ANY, "Tiempo de escaneo:")
        label_2.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Noto Sans"))
        grid_sizer_1.Add(label_2, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 5)
        grid_sizer_1.Add(self.txt_timeout, 0, wx.EXPAND, 0)
        sizer_13.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        sizer_13.Add((20, 20), 0, wx.EXPAND, 0)
        sizer_13.Add(self.btn_scan, 1, wx.ALL | wx.EXPAND, 5)
        sizer_13.Add((20, 20), 9, wx.EXPAND, 0)
        layout_tab_scanner.Add(sizer_13, 1, wx.ALL | wx.EXPAND, 10)
        self.tab_scan.SetSizer(layout_tab_scanner)
        sizer_7.Add(self.lista_redes, 1, wx.EXPAND, 0)
        self.tab_redes.SetSizer(sizer_7)
        sizer_11.Add(self.txt_output, 11, wx.ALL | wx.EXPAND, 5)
        sizer_12.Add((20, 20), 1, wx.ALL | wx.EXPAND, 0)
        sizer_12.Add(self.btn_clear_output, 0, wx.ALL | wx.EXPAND, 2)
        sizer_11.Add(sizer_12, 1, wx.EXPAND, 0)
        self.tab_output.SetSizer(sizer_11)
        self.tabs.AddPage(self.tab_scan, "Escanear")
        self.tabs.AddPage(self.tab_redes, "Redes")
        self.tabs.AddPage(self.tab_output, "Output")
        sizer_3.Add(self.tabs, 1, wx.ALL | wx.EXPAND, 1)
        self.SetSizer(sizer_3)
        self.Layout()
        # end wxGlade

    def on_combo_iface_changed(self, event):  # wxGlade: MainWin_Ui.<event_handler>
        print("Event handler 'on_combo_iface_changed' not implemented!")
        event.Skip()

    def on_btn_select_iface(self, event):  # wxGlade: MainWin_Ui.<event_handler>
        print("Event handler 'on_btn_select_iface' not implemented!")
        event.Skip()

    def on_btn_airmon_toggle(self, event):  # wxGlade: MainWin_Ui.<event_handler>
        print("Event handler 'on_btn_airmon_toggle' not implemented!")
        event.Skip()

    def on_btn_airmon_check(self, event):  # wxGlade: MainWin_Ui.<event_handler>
        print("Event handler 'on_btn_airmon_check' not implemented!")
        event.Skip()

    def on_btn_powerup(self, event):  # wxGlade: MainWin_Ui.<event_handler>
        print("Event handler 'on_btn_powerup' not implemented!")
        event.Skip()

    def on_btn_scan(self, event):  # wxGlade: MainWin_Ui.<event_handler>
        print("Event handler 'on_btn_scan' not implemented!")
        event.Skip()

    def on_lista_select_red(self, event):  # wxGlade: MainWin_Ui.<event_handler>
        print("Event handler 'on_lista_select_red' not implemented!")
        event.Skip()

    def on_button_clear_output(self, event):  # wxGlade: MainWin_Ui.<event_handler>
        print("Event handler 'on_button_clear_output' not implemented!")
        event.Skip()

# end of class MainWin_Ui
